<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Análise de Dados: Fundamentos de Estatística
Caderno de **Exercícios**<br>
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

Aluno: Raul Pichinin

# **Tópicos**

<ol type="1">
  <li>Média e Variância;</li>
  <li>Ordem e Posição;</li>
  <li>Correlação.</li>
</ol>

---

# **Exercícios**

## 1\. Tráfego de São Paulo

Neste exercício, vamos continuar a analisar os dados de mobilidade urbana da cidade de São Paulo. A base de dados está neste [link](https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/develop/dataset/traffic.csv) e é uma copia do dado original, presente neste [link](https://archive.ics.uci.edu/ml/datasets/Behavior+of+the+urban+traffic+of+the+city+of+Sao+Paulo+in+Brazil). A base de dados contem a quantidade de acidentes ocorridos na cidade entre 14/12/09 e 18/12/09, das 07:00h ás 20:00h, agregados em intervalos de 30 minutos.

In [1]:
!wget -q "https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/develop/dataset/traffic.csv" -O traffic.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('traffic.csv', sep=';')

In [4]:
df.head()

,hour,bus_stoped,broken_truck,vehicle_excess,accident_victim,running_over,fire_vehicles,occurrence_freight,incident__dangerous_freight,lack_electricity,fire,flooding,manifestations,defect_trolleybuses,tree_road,semaphore_off,intermittent_emaphore,slowness_traffic_%
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"4,1"
1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"6,6"
2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"8,7"
3,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"9,2"
4,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"11,1"

- **Exemplo**: (para relembrar)

O código abaixo extrai a 13ª linha do arquivo que representa a 14ª meia hora do dia 14/12/09, contadas a partir das 07:00h, ou seja, todos os incidentes ocorridos na cidade no dia em questão entre as 13:30h e 14:00h. Vemos, por exemplo, que dois ônibus e dois caminhões ficaram paradados nas ruas da cidade, atrapalhando o tráfego.

In [17]:
df.iloc[[13]]

,hour,bus_stoped,broken_truck,vehicle_excess,accident_victim,running_over,fire_vehicles,occurrence_freight,incident__dangerous_freight,lack_electricity,fire,flooding,manifestations,defect_trolleybuses,tree_road,semaphore_off,intermittent_emaphore,slowness_traffic_%
13,14,2,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,"4,9"

### **1.1. Agregação**

Neste primeira atividade, você deve gerar um array NumPy por dia. Para cada array você deve somar todos os incidentes que aconteceram naquela meia hora. Sendo assim, cada array deve ter 27 posições, cada qual com a soma dos incidentes daquela meira hora.

**Dica**: Você deve remover a primeira e a última coluna.

**Dica**: Os arrays devem ter os seguintes valores:

```python
14: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 2, 3]
15: [3, 0, 0, 0, 2, 4, 2, 1, 3, 0, 2, 0, 2, 3, 2, 2, 4, 7, 6, 3, 0, 1, 1, 5, 4, 6, 0]
16: [1, 1, 2, 4, 4, 5, 3, 2, 4, 2, 1, 1, 3, 6, 2, 0, 2, 8, 4, 6, 4, 1, 2, 7, 15, 4, 0]
17: [4, 1, 1, 0, 0, 0, 2, 3, 2, 7, 2, 1, 7, 3, 6, 4, 3, 2, 2, 3, 2, 5, 2, 0, 1, 4, 15]
18: [10, 1, 1, 5, 5, 7, 3, 4, 3, 1, 2, 3, 2, 2, 6, 2, 2, 4, 2, 3, 0, 3, 3, 2, 3, 6, 0]
```

In [12]:
import numpy as np

dia_14_df = df.loc[0:26].drop(columns=['hour']).drop(columns=['slowness_traffic_%'])
dia_15_df = df.loc[27:53].drop(columns=['hour']).drop(columns=['slowness_traffic_%'])
dia_16_df = df.loc[54:80].drop(columns=['hour']).drop(columns=['slowness_traffic_%'])
dia_17_df = df.loc[81:107].drop(columns=['hour']).drop(columns=['slowness_traffic_%'])
dia_18_df = df.loc[108:134].drop(columns=['hour']).drop(columns=['slowness_traffic_%'])

In [18]:
dia_14_df_transposed = dia_14_df.transpose()
dia_15_df_transposed = dia_15_df.transpose()
dia_16_df_transposed = dia_16_df.transpose()
dia_17_df_transposed = dia_17_df.transpose()
dia_18_df_transposed = dia_18_df.transpose()

In [19]:
dia_14_df_transposed_sum = dia_14_df_transposed.agg('sum')
dia_14_df_transposed_sum = pd.DataFrame([dia_14_df_transposed_sum], columns=dia_14_df_transposed.columns)
dia_14_df_transposed_sum

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2,2,3

In [21]:
dia_15_df_transposed_sum = dia_15_df_transposed.agg('sum')
dia_15_df_transposed_sum = pd.DataFrame([dia_15_df_transposed_sum], columns= dia_15_df_transposed.columns)
dia_15_df_transposed_sum

,27,28,29,30,31,32,33,34,35,36,...,44,45,46,47,48,49,50,51,52,53
0,3,0,0,0,2,4,2,1,3,0,...,7,6,3,0,1,1,5,4,6,0

In [22]:
dia_16_df_transposed_sum = dia_16_df_transposed.agg('sum')
dia_16_df_transposed_sum = pd.DataFrame([dia_16_df_transposed_sum], columns= dia_16_df_transposed.columns)
dia_16_df_transposed_sum

,54,55,56,57,58,59,60,61,62,63,...,71,72,73,74,75,76,77,78,79,80
0,1,1,2,4,4,5,3,2,4,2,...,8,4,6,4,1,2,7,15,4,0

In [23]:
dia_17_df_transposed_sum = dia_17_df_transposed.agg('sum')
dia_17_df_transposed_sum = pd.DataFrame([dia_17_df_transposed_sum], columns= dia_17_df_transposed.columns)
dia_17_df_transposed_sum

,81,82,83,84,85,86,87,88,89,90,...,98,99,100,101,102,103,104,105,106,107
0,4,1,1,0,0,0,2,3,2,7,...,2,2,3,2,5,2,0,1,4,15

In [24]:
dia_18_df_transposed_sum = dia_18_df_transposed.agg('sum')
dia_18_df_transposed_sum = pd.DataFrame([dia_18_df_transposed_sum], columns= dia_18_df_transposed.columns)
dia_18_df_transposed_sum

,108,109,110,111,112,113,114,115,116,117,...,125,126,127,128,129,130,131,132,133,134
0,10,1,1,5,5,7,3,4,3,1,...,4,2,3,0,3,3,2,3,6,0

In [25]:
dia_14_array = np.array(dia_14_df_transposed_sum)
dia_15_array = np.array(dia_15_df_transposed_sum)
dia_16_array = np.array(dia_16_df_transposed_sum)
dia_17_array = np.array(dia_17_df_transposed_sum)
dia_18_array = np.array(dia_18_df_transposed_sum)

In [28]:
print(f'Dia 14: {dia_14_array}\n Dia 15: {dia_15_array}\n Dia 16: {dia_16_array}\n Dia 17: {dia_17_array}\n Dia 18: {dia_18_array}')

Dia 14: [[0 0 0 0 0 0 0 0 0 0 0 1 0 5 2 0 0 0 0 0 1 0 0 0 2 2 3]]
 Dia 15: [[3 0 0 0 2 4 2 1 3 0 2 0 2 3 2 2 4 7 6 3 0 1 1 5 4 6 0]]
 Dia 16: [[ 1  1  2  4  4  5  3  2  4  2  1  1  3  6  2  0  2  8  4  6  4  1  2  7
  15  4  0]]
 Dia 17: [[ 4  1  1  0  0  0  2  3  2  7  2  1  7  3  6  4  3  2  2  3  2  5  2  0
   1  4 15]]
 Dia 18: [[10  1  1  5  5  7  3  4  3  1  2  3  2  2  6  2  2  4  2  3  0  3  3  2
   3  6  0]]

### **1.2. Métricas**

Para cada array você deve calcular as seguintes métricas:

 - **média**;
 - **desvio padrão**.

In [30]:
dia_14_media = np.mean(dia_14_array)
dia_14_desvio_padrao = np.std(dia_14_array)

dia_15_media = np.mean(dia_15_array)
dia_15_desvio_padrao = np.std(dia_15_array)

dia_16_media = np.mean(dia_16_array)
dia_16_desvio_padrao = np.std(dia_16_array)

dia_17_media = np.mean(dia_17_array)
dia_17_desvio_padrao = np.std(dia_17_array)

dia_18_media = np.mean(dia_18_array)
dia_18_desvio_padrao = np.std(dia_18_array)

print(f'Dia 14: media: {dia_14_media:.2f}, desvio padrao: {dia_14_desvio_padrao:.2f}\n Dia 15: media: {dia_15_media:.2f}, desvio padrao: {dia_15_desvio_padrao:.2f}\n Dia 16: media: {dia_16_media:.2f}, desvio padrao: {dia_16_desvio_padrao:.2f}\n Dia 17: media: {dia_17_media:.2f}, desvio padrao: {dia_17_desvio_padrao:.2f}\n Dia 18: media: {dia_18_media:.2f}, desvio padrao: {dia_18_desvio_padrao:.2f}')

Dia 14: media: 0.59, desvio padrao: 1.19
 Dia 15: media: 2.33, desvio padrao: 2.02
 Dia 16: media: 3.48, desvio padrao: 3.05
 Dia 17: media: 3.04, desvio padrao: 3.05
 Dia 18: media: 3.15, desvio padrao: 2.19

### **1.3. Interpretação**

Baseado nos resultados da questão 1.2, responda:

> Qual dia apresenta a maior média de acidentes por meia hora?

**Resposta:**
 Dia 16

> Qual dia apresenta a menor variação de acidentes por meia hora?

**Resposta:**
Dia 14

---